---
title: "Datos felinos costa rica"
author: "Erick Ruiz"
date: '2022-06-09'
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r carga_paquetes, message=FALSE}
#carga de paquetes

library(readr)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)
library(sf)
```

```{r lectura_datos_geoespacial, message= FALSE}
felinos_geoespacial <-
  st_read("felinos.csv",options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", 
      "Y_POSSIBLE_NAMES=decimalLatitude"  
    ),
    quiet = TRUE
  )


st_crs(felinos_geoespacial) <- 4326
```


```{r Lectura_datos_tabulares, message=FALSE}
 felinos <-
  read.delim("felinos.csv")
```
#Tabla

```{r Tabla}
felinos %>%
  dplyr::select(species,
                eventDate,
                stateProvince,
                locality,
                decimalLongitude,
                decimalLatitude) %>%
  datatable(
    colnames = c(
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    ),
    options = list(
      pageLength = 5,
      # cantidad de registros en una página
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json') # traducción al español
    ),
  )
```
# Grafico

```{r Grafico}
felinos %>%
  count(species) %>%
  ggplot(aes(x= reorder(species, n), y = n))+
  geom_bar(stat = "identity")+
  coord_flip() +
  ggtitle("cantidad de registros por especies")
xlab("Especie")
ylab("resgistro")
theme_minimal()
```

